export const FIND_POPULAR_MOVIES_REQUEST = 'FIND_POPULAR_MOVIES_REQUEST';
export const FIND_POPULAR_MOVIES_SUCCESS = 'FIND_POPULAR_MOVIES_SUCCESS';
export const FIND_POPULAR_MOVIES_FAILURE = 'FIND_POPULAR_MOVIES_FAILURE';

export const FIND_TOP_RATED_MOVIES_REQUEST = 'FIND_TOP_RATED_MOVIES_REQUEST';
export const FIND_TOP_RATED_MOVIES_SUCCESS = 'FIND_TOP_RATED_MOVIES_SUCCESS';
export const FIND_TOP_RATED_MOVIES_FAILURE = 'FIND_TOP_RATED_MOVIES_FAILURE';
