export const FIND_POPULAR_MOVIES_REQUEST = 'FIND_POPULAR_MOVIES_REQUEST';
export const FIND_POPULAR_MOVIES_SUCCESS = 'FIND_POPULAR_MOVIES_SUCCESS';
export const FIND_POPULAR_MOVIES_FAILURE = 'FIND_POPULAR_MOVIES_FAILURE';

export const FIND_TOP_RATED_MOVIES_REQUEST = 'FIND_TOP_RATED_MOVIES_REQUEST';
export const FIND_TOP_RATED_MOVIES_SUCCESS = 'FIND_TOP_RATED_MOVIES_SUCCESS';
export const FIND_TOP_RATED_MOVIES_FAILURE = 'FIND_TOP_RATED_MOVIES_FAILURE';

export const FIND_POPULAR_TV_REQUEST = 'FIND_POPULAR_TV_REQUEST';
export const FIND_POPULAR_TV_SUCCESS = 'FIND_POPULAR_TV_SUCCESS';
export const FIND_POPULAR_TV_FAILURE = 'FIND_POPULAR_TV_FAILURE';

export const FIND_TOP_RATED_TV_REQUEST = 'FIND_TOP_RATED_TV_REQUEST';
export const FIND_TOP_RATED_TV_SUCCESS = 'FIND_TOP_RATED_TV_SUCCESS';
export const FIND_TOP_RATED_TV_FAILURE = 'FIND_TOP_RATED_TV_FAILURE';
